outline <- list(
  
  "Figure_1" = list(
    figure_id = "Figure_1",
    panel = "A",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c(
      "q46c_G2", "q46f_G2", "q46g_G2", "q46c_G1", "q46e_G2", "q46d_G2", "q46f_G1", 
      "q46a_G2", "q46a_G2", "q46e_G1", "q46h_G2"
    ),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "None",
    type = "Large Dumbbells",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_X" = list(
    figure_id = "Figure_1_X",
    panel = "A",
    chart_title = "Fundamental Freedoms in Thailand, by area of residence",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c(
      "q46c_G2", "q46f_G2", "q46g_G2", "q46c_G1", "q46e_G2", "q46d_G2", "q46f_G1", 
      "q46a_G2", "q46a_G2", "q46e_G1", "q46h_G2"
    ),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "None",
    type = "Large Dumbbells",
    legend_text = c("Urban", "Rural"),
    legend_eqs = c("Urban", "Rural"),
    legend_color = c("#35605A","#00120B"),
    sample = c("Urban", "Rural"),
    years = c("2025")
  ),
  
  "Figure_1_Y" = list(
    figure_id = "Figure_1_X",
    panel = "A",
    chart_title = "Fundamental Freedoms in Thailand, by gender",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c(
      "q46c_G2", "q46f_G2", "q46g_G2", "q46c_G1", "q46e_G2", "q46d_G2", "q46f_G1", 
      "q46a_G2", "q46a_G2", "q46e_G1", "q46h_G2"
    ),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "None",
    type = "Large Dumbbells",
    legend_text = c("Female", "Male"),
    legend_eqs = c("Female", "Male"),
    legend_color = c("#35605A","#00120B"),
    sample = c("Female", "Male"),
    years = c("2025")
  ),
  
  "Figure_2_1" = list(
    figure_id = "Figure_2_1",
    panel = "A",
    chart_title = "Discrimination Experiences in Thailand over Time",
    chart_subtitle = "Percentage of respondents who reported having experienced some form of discrimination in the last year",
    var_id = c("discrimination1"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Bars",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#a90099", "#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_2_2" = list(
    figure_id = "Figure_2_2",
    panel = "A",
    chart_title = "Reasons Why People Feel Discriminated",
    chart_subtitle = "Percentage of respondents who think that the main reason why they experience discrimination is due to their…",
    var_id = c("q17_1", "q17_2", "q17_3", "q17_4", "q17_7", "q17_11", "q17_12", "q17_13", "q17_14"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Bars",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2025")
  ),

  "Figure_3" = list(
    figure_id = "Figure_3",
    panel = "A",
    chart_title = "Perceptions of the Judiciary",
    chart_subtitle = "Percentage of respondents who believes that…",
    var_id = c("q48g_G2", "q48f_G2", "q48e_G1", "q48g_G1", "q48f_G1"),
    reportValues = c("1", "2"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Radar",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_4_A" = list(
    figure_id = "Figure_4",
    panel = "B",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents who believe that most or all people working in the following institutions are corrupt",
    var_id = c("q2a"),
    reportValues = c("3", "4"),
    panel_title = "Members of Congress",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_4_B" = list(
    figure_id = "Figure_4",
    panel = "B",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents who believe that most or all people working in the following institutions are corrupt",
    var_id = c("q2d"),
    reportValues = c("3", "4"),
    panel_title = "Police Officers",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_4_C" = list(
    figure_id = "Figure_4",
    panel = "C",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents who believe that most or all people working in the following institutions are corrupt",
    var_id = c("q2c", "q2b"),
    reportValues = c("3", "4"),
    panel_title = "Executive",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("National Government Officers", "Local Government Officers"),
    legend_eqs = c("q2c", "q2b"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_4_D" = list(
    figure_id = "Figure_4",
    panel = "D",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents who believe that most or All people working in the following institutions are corrupt",
    var_id = c("q2e", "q2g", "q2f"),
    reportValues = c("3", "4"),
    panel_title = "Justice System",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges & Magistrates", "Public Defense Attorneys"),
    legend_eqs = c("q2e", "q2g", "q2f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_5_1" = list(
    figure_id = "Figure_5",
    panel = "A",
    chart_title = "Perceptions of Accountability in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree that high-ranking government officials would be held accountable for breaking the law…",
    var_id = c("q43_G2"),
    reportValues = c("3"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Bars",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#a90099", "#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_5_2" = list(
    figure_id = "Figure_5",
    panel = "A",
    chart_title = "Bribery Victimization in Thailand over Time",
    chart_subtitle = "Percentage of respondents who paid a bribe in the last three years to access the following services",
    var_id = c("q4a", "q4b", "q4c", "q4d", "q4e"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Single Dumbbells",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#a90099", "#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_6_A" = list(
    figure_id = "Figure_6",
    panel = "A",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1a"),
    reportValues = c("1", "2"),
    panel_title = "People Living in Their Country",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_6_B" = list(
    figure_id = "Figure_6",
    panel = "B",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1d"),
    reportValues = c("1", "2"),
    panel_title = "Police Officers",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_6_C" = list(
    figure_id = "Figure_6",
    panel = "C",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1b", "q1c"),
    reportValues = c("1", "2"),
    panel_title = "Executive",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("National Government Officers", "Local Government Officers"),
    legend_eqs = c("q1b", "q1c"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_6_D" = list(
    figure_id = "Figure_6",
    panel = "D",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1e", "q1g", "q1f"),
    reportValues = c("1", "2"),
    panel_title = "Justice System",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges & Magistrates", "Public Defense Attorneys"),
    legend_eqs = c("q1e", "q1g", "q1f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_7_1" = list(
    figure_id = "Figure_7",
    panel = "A",
    chart_title = "Types of Crimes Experienced by People in Thailand",
    chart_subtitle = "Victimization rate, by type of crime",
    var_id = c("crime1", "crime2", "crime3", "crime4"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Lollipops",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2025")
  ),

  "Figure_7_2" = list(
    figure_id = "Figure_7",
    panel = "A",
    chart_title = "Crime Reporting in Thailand",
    chart_subtitle = "Percentage of Respondents",
    var_id = c("q8d"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Waffle",
    legend_text = c("2025"),
    legend_eqs = c("2025"),
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2025")
  ),

  "Figure_8_1" = list(
    figure_id = "Figure_8",
    panel = "A",
    chart_title = "Perceptions of Security in Thailand over Time",
    chart_subtitle = "Percentage of respondents who reported that they feel safe or very safe walking in their neighborhood at night",
    var_id = c("q9"),
    reportValues = c("1", "2"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Bars",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#a90099", "#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_8_2" = list(
    figure_id = "Figure_8",
    panel = "A",
    chart_title = "Impact of Sociodemographic Characteristics on Perceptions of Safety",
    chart_subtitle = "Likelihood that respondents feel safe or very safe walking in their neighborhood at night",
    var_id = "q9",
    type = "Logit",
    sample = "National",
    years = c("2025")
  ),

  "Figure_9" = list(
    figure_id = "Figure_9",
    panel = "A",
    chart_title = "Perceptions of the Criminal Justice System in Thailand",
    chart_subtitle = "Percentage of respondents who are confident or very confident that the criminal justice system…",
    var_id = c("q49a", "q49b_G2", "q49e_G2", "q49c_G2", "q49e_G1", "q49d_G1", "q49c_G1", "q49b_G1"),
    reportValues = c("1", "2"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Radar",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_9_Y" = list(
    figure_id = "Figure_9",
    panel = "A",
    chart_title = "Perceptions of the Criminal Justice System in Thailand, by gender",
    chart_subtitle = "Percentage of respondents who are confident or very confident that the criminal justice system…",
    var_id = c("q49a", "q49b_G2", "q49e_G2", "q49c_G2", "q49e_G1", "q49d_G1", "q49c_G1", "q49b_G1"),
    reportValues = c("1", "2"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Radar",
    legend_text = c("Female", "Male"),
    legend_eqs = c("Female", "Male"),
    legend_color = c("#35605A","#00120B"),
    sample = c("Female", "Male"),
    years = c("2025")
  ),

  "Figure_10_A" = list(
    figure_id = "Figure_10",
    panel = "A",
    chart_title = "Criminal Justice Actors",
    chart_subtitle = "Perceptions of criminal justice actors in the United States",
    var_id = c("q1e", "q1g", "q1f"),
    reportValues = c("1", "2"),
    panel_title = "Trust",
    panel_subtitle = "Percentage of respondents who have a lot or some trust in prosecutors, public defense attorneys, and judges and magistrates",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges and magistrates", "Public defense attorneys"),
    legend_eqs = c("q1e", "q1g", "q1f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_10_B" = list(
    figure_id = "Figure_10",
    panel = "B",
    chart_title = "Criminal Justice Actors",
    chart_subtitle = "Perceptions of criminal justice actors in the United States",
    var_id = c("q2e", "q2g", "q2f"),
    reportValues = c("3", "4"),
    panel_title = "Corruption",
    panel_subtitle = "Percentage of respondents who believe that most or All prosecutors, public defense attorneys, and judges and magistrates are corrupt",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges and magistrates", "Public defense attorneys"),
    legend_eqs = c("q2e", "q2g", "q2f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),

  "Figure_10_C" = list(
    figure_id = "Figure_10",
    panel = "C",
    chart_title = "Criminal Justice Actors",
    chart_subtitle = "Perceptions of criminal justice actors in the United States",
    var_id = c("q48f_G2", "q48g_G2", "q48h_G1"),
    reportValues = c("1", "2"),
    panel_title = "Independence",
    panel_subtitle = "Percentage of respondents who believe that prosecutors, public defense attorneys, and judges and magistrates do their job well",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges and magistrates", "Public defense attorneys"),
    legend_eqs = c("q48f_G2", "q48g_G2", "q48h_G1"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  )
)
