outline <- list(
  "Figure_1_A" = list(
    figure_id = "Figure_1",
    panel = "A",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46c_G2"),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "People can express opinions against the government",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_B" = list(
    figure_id = "Figure_1",
    panel = "B",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46f_G2"),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "Civil society organizations can express opinions against the government",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_C" = list(
    figure_id = "Figure_1",
    panel = "C",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46g_G2"),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "Political parties can express opinions against the government",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_D" = list(
    figure_id = "Figure_1",
    panel = "D",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46c_G1"),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "The media can express opinions against the government withoutfear of retaliation",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_E" = list(
    figure_id = "Figure_1",
    panel = "E",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46e_G2"),
    reportValues = c("1", "2"),
    panel_title = "Expression",
    panel_subtitle = "The media can expose cases of corruption",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_F" = list(
    figure_id = "Figure_1",
    panel = "F",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46d_G2"),
    reportValues = c("1", "2"),
    panel_title = "Participation",
    panel_subtitle = "People can attend community meetings",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_G" = list(
    figure_id = "Figure_1",
    panel = "G",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46f_G1"),
    reportValues = c("1", "2"),
    panel_title = "Participation",
    panel_subtitle = "People can join any political organization",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_H" = list(
    figure_id = "Figure_1",
    panel = "H",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46a_G2"),
    reportValues = c("1", "2"),
    panel_title = "Participation",
    panel_subtitle = "People can organize around an issue or petition",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_I" = list(
    figure_id = "Figure_1",
    panel = "I",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46d_G1"),
    reportValues = c("1", "2"),
    panel_title = "Elections",
    panel_subtitle = "Local government officials are elected through a clean process",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_J" = list(
    figure_id = "Figure_1",
    panel = "J",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46e_G1"),
    reportValues = c("1", "2"),
    panel_title = "Elections",
    panel_subtitle = "People can vote freely without feeling harassed or pressured",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_1_K" = list(
    figure_id = "Figure_1",
    panel = "K",
    chart_title = "Fundamental Freedoms in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree on the following statements…",
    var_id = c("q46h_G2"),
    reportValues = c("1", "2"),
    panel_title = "Religion",
    panel_subtitle = "Religious minorities can observe their holy days",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  # "Figure_2_A" = list(
  #   figure_id = "Figure_2",
  #   panel = "A",
  #   chart_title = "Discrimination Experiences in Thailand",
  #   chart_subtitle = "Percentage of respondents who reported having experienced some form of discrimination in the last year",
  #   var_id = c("discrimination1"),
  #   reportValues = c("1"),
  #   panel_title = "None",
  #   panel_subtitle = "None",
  #   type = "Waffle",
  #   legend_text = "None",
  #   legend_color = c("#2a2a94"),
  #   sample = "National",
  #   years = c("2025")
  # ),
  
  "Figure_3_A" = list(
    figure_id = "Figure_3",
    panel = "A",
    chart_title = "Discrimination Experiences in Thailand over Time",
    chart_subtitle = "Percentage of respondents who reported having experienced some form of discrimination in the last year",
    var_id = c("discrimination1"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Bars",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_4_A" = list(
    figure_id = "Figure_4",
    panel = "A",
    chart_title = "Reasons Why People Feel Discriminated",
    chart_subtitle = "Percentage of respondents who think that the main reason why they experience discrimination is due to their…",
    var_id = c("q17_1", "q17_2", "q17_3", "q17_4", "q17_7", "q17_11", "q17_12", "q17_13", "q17_14"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Bars",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2025")
  ),
  
  "Figure_5_A" = list(
    figure_id = "Figure_5",
    panel = "A",
    chart_title = "Perceptions of the Judiciary",
    chart_subtitle = "Percentage of respondents who believes that…",
    var_id = c("q48g_G2"),
    reportValues = c("1", "2"),
    panel_title = "Judges decide cases in an independent manner.",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2016", "2018", "2025")
  ),
  
  "Figure_5_B" = list(
    figure_id = "Figure_5",
    panel = "B",
    chart_title = "Perceptions of the Judiciary",
    chart_subtitle = "Percentage of respondents who believes that…",
    var_id = c("q48f_G2"),
    reportValues = c("1", "2"),
    panel_title = "Prosecutors prosecute crimes in an independent manner.",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_5_C" = list(
    figure_id = "Figure_5",
    panel = "C",
    chart_title = "Perceptions of the Judiciary",
    chart_subtitle = "Percentage of respondents who believes that…",
    var_id = c("q48e_G1"),
    reportValues = c("1", "2"),
    panel_title = "Courts guarantee everyone a fair trial.",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_5_D" = list(
    figure_id = "Figure_5",
    panel = "D",
    chart_title = "Perceptions of the Judiciary",
    chart_subtitle = "Percentage of respondents who believes that…",
    var_id = c("q48g_G1"),
    reportValues = c("3", "4"),
    panel_title = "Courts are not biased towards money or influence.",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_6_A" = list(
    figure_id = "Figure_6",
    panel = "A",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents in the United States who believe that most or All people working in the following institutions are corrupt …",
    var_id = c("q2a"),
    reportValues = c("3", "4"),
    panel_title = "Members of Congress",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_6_B" = list(
    figure_id = "Figure_6",
    panel = "B",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents in the United States who believe that most or All people working in the following institutions are corrupt …",
    var_id = c("q2d"),
    reportValues = c("3", "4"),
    panel_title = "Police Officers",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_6_C" = list(
    figure_id = "Figure_6",
    panel = "C",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents in the United States who believe that most or All people working in the following institutions are corrupt …",
    var_id = c("q2c", "q2b"),
    reportValues = c("3", "4"),
    panel_title = "Executive",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("National Government Officers", "Local Government Officers"),
    legend_eqs = c("q2c", "q2b"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_6_D" = list(
    figure_id = "Figure_6",
    panel = "D",
    chart_title = "Perceptions of Corruption by Institution over Time",
    chart_subtitle = "Percentage of respondents in the United States who believe that most or All people working in the following institutions are corrupt …",
    var_id = c("q2e", "q2g", "q2f"),
    reportValues = c("3", "4"),
    panel_title = "Justice System",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges & Magistrates", "Public Defense Attorneys"),
    legend_eqs = c("q2e", "q2g", "q2f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_7_A" = list(
    figure_id = "Figure_7",
    panel = "A",
    chart_title = "Perceptions of Accountability in Thailand over Time",
    chart_subtitle = "Percentage of respondents who agree or strongly agree that high-ranking government officials would be held accountable for breaking the law…",
    var_id = c("q43_G2"),
    reportValues = c("3"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  # "Figure_8_A" = list(
  #   figure_id = "Figure_8",
  #   panel = "A",
  #   chart_title = "Perceptions of Accountability, by TBD",
  #   chart_subtitle = "Percentage of respondents who agree or strongly agree that high-ranking government officials would be held accountable for breaking the law…",
  #   var_id = c("q43_G2"),
  #   reportValues = c("3"),
  #   panel_title = "None",
  #   panel_subtitle = "None",
  #   type = "Bars",
  #   legend_text = "TBD",
  #   legend_color = c("#3273ff", "#a90099"),
  #   sample = "TBD",
  #   years = c("2025")
  # ),
  
  "Figure_9_A" = list(
    figure_id = "Figure_9",
    panel = "A",
    chart_title = "Bribery Victimization in Thailand over Time",
    chart_subtitle = "Percentage of respondents who paid a bribe in the last three years to access the following services, out of those who used these services",
    var_id = c("q4a", "q4b", "q4c", "q4d", "q4e"),
    reportValues = c("1"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Dumbbells",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#a90099", "#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_10_A" = list(
    figure_id = "Figure_10",
    panel = "A",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1a"),
    reportValues = c("1", "2"),
    panel_title = "People Living in Their Country",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_10_B" = list(
    figure_id = "Figure_10",
    panel = "B",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1d"),
    reportValues = c("1", "2"),
    panel_title = "Police Officers",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_10_C" = list(
    figure_id = "Figure_10",
    panel = "C",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1b", "q1c"),
    reportValues = c("1", "2"),
    panel_title = "Executive",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("National Government Officers", "Local Government Officers"),
    legend_eqs = c("q1b", "q1c"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_10_D" = list(
    figure_id = "Figure_10",
    panel = "D",
    chart_title = "Trust in Institutions over Time",
    chart_subtitle = "Percentage of respondents who have a lot or some trust in...",
    var_id = c("q1e", "q1g", "q1f"),
    reportValues = c("1", "2"),
    panel_title = "Justice System",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges & Magistrates", "Public Defense Attorneys"),
    legend_eqs = c("q1e", "q1g", "q1f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_11_A" = list(
    figure_id = "Figure_11",
    panel = "A",
    chart_title = "Perceptions of Security in Thailand over Time",
    chart_subtitle = "Percentage of respondents who reported that they feel safe or very safe walking in their neighborhood at night",
    var_id = c("q9"),
    reportValues = c("1", "2"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Slopes",
    legend_text = "None",
    legend_eqs = "None",
    legend_color = c("#2a2a94"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_12_A" = list(
    figure_id = "Figure_12",
    panel = "A",
    chart_title = "Perceptions of the Criminal Justice System in Thailand",
    chart_subtitle = "Percentage of respondents who are confident or very confident that the criminal justice system…",
    var_id = c("q49a", "q49b_G2", "q49e_G2", "q49c_G2", "q49e_G1", "q49d_G1", "q49c_G1", "q49b_G1"),
    reportValues = c("1", "2"),
    panel_title = "None",
    panel_subtitle = "None",
    type = "Radar",
    legend_text = c("2018", "2025"),
    legend_eqs = c("2018", "2025"),
    legend_color = c("#2a2a94", "#a90099"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_13_A" = list(
    figure_id = "Figure_13",
    panel = "A",
    chart_title = "Criminal Justice Actors",
    chart_subtitle = "Perceptions of criminal justice actors in the United States",
    var_id = c("q1e", "q1g", "q1f"),
    reportValues = c("1", "2"),
    panel_title = "Trust",
    panel_subtitle = "Percentage of respondents who have a lot or some trust in prosecutors, public defense attorneys, and judges and magistrates",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges and magistrates", "Public defense attorneys"),
    legend_eqs = c("q1e", "q1g", "q1f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_13_B" = list(
    figure_id = "Figure_13",
    panel = "B",
    chart_title = "Criminal Justice Actors",
    chart_subtitle = "Perceptions of criminal justice actors in the United States",
    var_id = c("q2e", "q2g", "q2f"),
    reportValues = c("3", "4"),
    panel_title = "Corruption",
    panel_subtitle = "Percentage of respondents who believe that most or All prosecutors, public defense attorneys, and judges and magistrates are corrupt",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges and magistrates", "Public defense attorneys"),
    legend_eqs = c("q2e", "q2g", "q2f"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  ),
  
  "Figure_13_C" = list(
    figure_id = "Figure_13",
    panel = "C",
    chart_title = "Criminal Justice Actors",
    chart_subtitle = "Perceptions of criminal justice actors in the United States",
    var_id = c("q48f_G2", "q48g_G2", "q48h_G1"),
    reportValues = c("1", "2"),
    panel_title = "Independence",
    panel_subtitle = "Percentage of respondents who believe that prosecutors, public defense attorneys, and judges and magistrates do their job well",
    type = "Slopes",
    legend_text = c("Prosecutors", "Judges and magistrates", "Public defense attorneys"),
    legend_eqs = c("q48f_G2", "q48g_G2", "q48h_G1"),
    legend_color = c("#2a2a94", "#a90099", "#3273ff"),
    sample = "National",
    years = c("2018", "2025")
  )
)
